table 'Currency Selection'
	lineageTag: a0ec6b4e-79fd-4e86-b868-c1123f15c10c

	column Currency
		dataType: string
		lineageTag: cd9443aa-d9ba-488b-9dc8-d16f17fecff1
		summarizeBy: none
		sourceColumn: Currency
		sortByColumn: CurrencyOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column CurrencyOrder
		dataType: int64
		formatString: 0
		lineageTag: 3bd86aa4-60ed-499f-a1c8-edaa4627f32b
		summarizeBy: sum
		sourceColumn: CurrencyOrder

		annotation SummarizationSetBy = Automatic

	partition 'Currency Selection' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCg12UdJRMlSK1YlWCnYMArKNlGJjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Currency = _t, CurrencyOrder = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Currency", type text}, {"CurrencyOrder", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

